version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      github-actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directories:
      - "plugins/guardrails/hooks/permission-gate/**/*"
    target-branch: "main"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      gomod-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      gomod-security:
        applies-to: security-updates
        patterns:
          - "*"
